#!/bin/sh

# Abort on error.
set -e -o pipefail

MKPICO_TARGET="arm-none-eabi"
MKPICO_BUILD=$(uname -m)
MKPICO_HOST=${MKPICO_BUILD}

MKPICO_ROOT=`pwd`
MKPICO_LOG_DIR="${MKPICO_ROOT}/log"
MKPICO_BUILD_DIR="${MKPICO_ROOT}/build"
MKPICO_SOURCE_DIR="${MKPICO_ROOT}/source"
MKPICO_CROSS_TOOLS="${MKPICO_ROOT}/cross-tools"

MKPICO_LOG_HISTORY=3

MKPICO_PREFIX="${MKPICO_CROSS_TOOLS}"

MKPICO_CFLAGS="-O2 -pipe -fPIC"
MKPICO_CXXFLAGS="-O2 -pipe -fPIC"
MKPICO_LDFLAGS=""

MKPICO_CORES=$(grep -c '^processor' /proc/cpuinfo)

GNU_MIRROR="https://ftp.gnu.org/gnu/"
GNU_KEYRING="gnu-keyring.gpg"

# Package information
BINUTILS_VERSION="2.35"
BINUTILS_URL="${GNU_MIRROR}/binutils"

GCC_VERSION="10.2.0"
GCC_URL="${GNU_MIRROR}/gcc/gcc-${GCC_VERSION}"

GCC_INFRASTRUCTIRE_URL="https://gcc.gnu.org/pub/gcc/infrastructure/"

GDB_VERSION="10.1"
GDB_URL="${GNU_MIRROR}/gdb"

NEWLIB_VERSION="4.1.0"
NEWLIB_URL="https://sourceware.org/pub/newlib/"

MKPICO_VERSION="0.1"
MKPICO_USAGE=$(cat <<EOF
Usage: $(basename "${0}") [-hv]
Builds a full featured ${MKPICO_TARGET} toolchain for the RaspberryPi Pico
including a gcc, newlib and an optional gdb.

-h|--help:
	Displays this help.
-v|--version:
	Displays the current version of this script.
-l|--latest:
	This will check upstream for newer versions of the specified libraries
	and try to build with these latest package versions. If specific versions
	are set using the corresponding --build-* option, this version will be used.
-d|--dump-latest:
	Dumps a list of the latest available version.
-p|--prefix:
	Installation prefix (default ${MKPICO_PREFIX}).
--build-gcc:
	Build the specified version of the ${MKPICO_TARGET} (default ${GCC_VERSION}).
--build-newlib:
	Build the specified version of the newlib (default ${NEWLIB_VERSION}).
--build-gdb:
	Build the specified version of the GNU debugger (default ${GDB_VERSION}).

All --build-* options may be followed by a space seperated package version.
In this case $(basename "${0}") will always attempt to build the custom
versions even if --latest is used.
EOF
)

# Helper functions.
pushd() {
	command pushd "$@" > /dev/null
}

popd() {
	command popd > /dev/null
}

info() {
	echo -e "\033[94mINFO:\033[39m $*" >&2
}

warning() {
	echo -e "\033[33mCAUTION:\033[39m $*" >&2
}

usage() {
	local rc=0

	if [ -n "${1}" ]; then
		rc="${1}"
	fi

	if [ -n "${2}" ]; then
		echo -e "ERROR: ${2}\n"
	fi

	echo "${MKPICO_USAGE}"

	exit "${rc}"
}

hasValue() {
	if [ -n "${1}" ] && ! case "${1}" in -*) true;; *) false;; esac; then
		return 0
	fi

	return 1
}

# TODO: Add option to disable isl build.
parseOptions() {
	local nextOpt=0

	# Parse the command line parameters.
	while [ -n "${1+xxx}" ]; do
		case "${1}" in
			-h|--help)
				usage
				;;
			-v|--version)
				;;
			-l|--latest)
				;;
			-d|--dump-latest)
				dumpLatest
				exit 0
				;;
			-p|--prefix)
				if hasValue "${2}"; then
					MKPICO_PREFIX="${2}"
					shift
				else
					usage 1 "Missing value for option ${1}"
				fi

				;;
			--build-gcc)
				if hasValue "${2}"; then
					GCC_VERSION="${2}"
					shift
				else
					usage 1 "Missing value for option ${1}"
				fi

				;;
			--build-newlib)
				if hasValue "${2}"; then
					NEWLIB_VERSION="${2}"
					shift
				else
					usage 1 "Missing value for option ${1}"
				fi

				;;
			--build-gdb)
				if hasValue "${2}"; then
					GDB_VERSION="${2}"
					shift
				fi

				;;
			-*)
				usage 1 "Unrecognized option: ${1}"
				;;
			*)
				break
				;;
		esac

		shift
	done
}

logrotate() {
	LOG_DIR=$1
	FILE=$2
	COUNT=$3

	if [ ! -d "${LOG_DIR}" ]; then
		mkdir -p "${LOG_DIR}"
	fi

	if [ -f "${LOG_DIR}/${FILE}.${COUNT}" ]; then
		rm "${LOG_DIR}/${FILE}.${COUNT}"
	fi

	while (( --COUNT >= 0 )); do
		if [ -f "${LOG_DIR}/${FILE}.${COUNT}" ]; then
			mv "${LOG_DIR}/${FILE}.${COUNT}" "${LOG_DIR}/${FILE}.$((COUNT+1))"
		fi
	done

	if [ -f "${LOG_DIR}/${FILE}" ]; then
		mv "${LOG_DIR}/${FILE}" "${LOG_DIR}/${FILE}.0"
	fi
}

findPackages() {
	local url="${1}"
	if [ -z "${url}" ]; then
		echo "No remote server url given"
		exit 1
	fi

	local prefix="${2}"
	if [ -z "${prefix}" ]; then
		echo "no package prefix given"
		exit 1
	fi

	curl -k -L ${url} 2>/dev/null \
		| sed -n "s/.*href=\"[^\"]*\(${prefix}\([0-9]\+\(\.[0-9]\+\)\?\(\.[0-9]\+\)\?\(\.[0-9]\+\)\?\)[^\"]*\).*/\1/p"
}

findLatestPackage() {
	local listing="$(findPackages "${1}" "${2}")"

	echo "${listing}" \
		| sort -fir \
		| head -n 1
}

findLatestVersion() {
	latestPackage="$(findLatestPackage "${1}" "${2}")"

	echo "${latestPackage}" \
		| sed -n "s/${2}\([0-9]\+\(\.[0-9]\+\)\?\(\.[0-9]\+\)\?\(\.[0-9]\+\)\?\).*/\1/p"
}

dumpLatest() {
	printf "%-15s %-10s\n" "Package" "Version"
	printf "%15s %10s\n" "binutils" "$(findLatestVersion "${BINUTILS_URL}" "binutils-")"
	printf "%15s %10s\n" "gcc" "$(findLatestVersion "${GCC_URL}" "gcc-")"
	printf "%15s %10s\n" "mpfr" "$(findLatestVersion "${GCC_INFRASTRUCTIRE_URL}" "mpfr-")"
	printf "%15s %10s\n" "mpc" "$(findLatestVersion "${GCC_INFRASTRUCTIRE_URL}" "mpc-")"
	printf "%15s %10s\n" "gmp" "$(findLatestVersion "${GCC_INFRASTRUCTIRE_URL}" "gmp-")"
	printf "%15s %10s\n" "isl" "$(findLatestVersion "${GCC_INFRASTRUCTIRE_URL}" "isl-")"
	printf "%15s %10s\n" "gdb" "$(findLatestVersion "${GDB_URL}" "gdb-")"
	printf "%15s %10s\n" "newlib" "$(findLatestVersion "${NEWLIB_URL}" "newlib-")"
}

extract() {
	local file="${1}"
	local filename="$(echo "${file}" | awk '{print tolower($0)}')"

	info "Extracting ${file}"

	local target=""
	if [ -n "${2}" ] && [ -d "${2}" ]; then
		target="$(readlink -f "${2}")"
	fi

	pushd "${target}"
	case "${filename}" in
		*.tar* | *.tbz | *.tgz)
			tar xf "${file}" ;;
		*.lzma) unlzma "${file}" ;;
		*.bz2) bunzip2 "${file}" ;;
		*.rar) unrar x -ad "${file}" ;;
		*.gz) gunzip "${file}" ;;
		*.zip) unzip "${file}" ;;
		*.Z) uncompress "${file}" ;;
		*.7z) 7z x "${file}" ;;
		*.xz) unxz "${file}" ;;
		*)
			popd
			echo "extract: '${file}' - unknown archive method"
			return 1
			;;
	esac
	popd

	return 0
}

isValidSignature() {
	gpg --verify --keyring "${MKPICO_SOURCE_DIR}/${1}" "${MKPICO_SOURCE_DIR}/${2}"
}

download() {
	local url="${1}"
	local file="${2}"
	local signature="${3}"

	if [ -n "${signature}" ]; then
		if ! [ -f "${MKPICO_SOURCE_DIR}/${signature}" ]; then
			info "Downloading ${signature}"
			# TODO: Downloading with -k is insecure, however currently the gnu cacert does not work.
			curl -L -k -o "${MKPICO_SOURCE_DIR}/${signature}" "${url}/${signature}"
		else
			warning "Using signature ${signature} from cache - skipping"
		fi
	fi

	if [ -f "${MKPICO_SOURCE_DIR}/${file}" ]; then
		# Check using signature if file is corrupted and skip file if not.
		if [ -n "${signature}" ] && isValidSignature "${GNU_KEYRING}" "${signature}" ; then
			warning "${file} in cache - skipping."
		else
			warning "Using unsigned ${file} from cache - skipping "
		fi

		return
	fi

	info "Downloading ${file}"
	# TODO: Downloading with -k is insecure, however currently the gnu cacert does not work.
	curl -L -k -o "${MKPICO_SOURCE_DIR}/${file}" "${url}/${file}"

	info "Verifying signature"
	# TODO: Check using signature if download was successful
	# Check using signature if file is corrupted and skip file if not.
	if [ -n "${signature}" ] && ! isValidSignature "${GNU_KEYRING}" "${signature}" ; then
		warning "${file} has invalid signature."
	fi
}

downloadExtract() {
	download "${1}" "${2}" "${3}"
	extract "${MKPICO_SOURCE_DIR}/${2}" "${MKPICO_BUILD_DIR}"
}

buildPackage() {
	local package="${1}"
	local package_version="${2}"
	local package_url="${3}"
	local package_name="${4}"
	local package_signature="${5}"

	shift 5

	local real_package="${package}"
	if [ "${package}" = "gcc-stage1" ]; then
		real_package="gcc"
	fi

	if ! [ "${package}" = "gcc" ]; then
		downloadExtract "${package_url}" "${package_name}" "${package_signature}"
	fi

	# Download prerequisits for gcc.
	if [ "${package}" = "gcc-stage1" ]; then
		info "Checking for contrib/download_prerequisites"
		if [ -f "${MKPICO_BUILD_DIR}/${real_package}-${package_version}/contrib/download_prerequisites" ]; then
			info "Downloading gcc prerequisites"
			pushd "${MKPICO_BUILD_DIR}/${real_package}-${package_version}"
			# This script also creates links in the build directory
			./contrib/download_prerequisites \
				--directory=${MKPICO_SOURCE_DIR} \
				--isl --verify --sha512 --no-force
			popd
		fi
	fi

	mkdir -p "${MKPICO_BUILD_DIR}/${package}"
	pushd "${MKPICO_BUILD_DIR}/${package}"

	info "Configuring ${package}"

	logrotate "${MKPICO_LOG_DIR}" "${package}-configure.log" "${MKPICO_LOG_HISTORY}"

	if [ "${package}" = "gcc" ]; then
		CFLAGS="${MKPICO_CFLAGS} -I${MKPICO_PREFIX}/include" \
		CXXFLAGS="${MKPICO_CXXFLAGS} -I${MKPICO_PREFIX}/include" \
		LDFLAGS="-L${MKPICO_PREFIX}/lib" \
		../"${real_package}"-"${package_version}"/configure "${@}" 2>&1 \
			| tee "${MKPICO_LOG_DIR}/${package}-configure.log"
	else
		CFLAGS="${MKPICO_CFLAGS}" \
		CXXFLAGS="${MKPICO_CXXFLAGS}" \
		LDFLAGS="${MKPICO_LDFLAGS}" \
		../"${real_package}"-"${package_version}"/configure "${@}" 2>&1 \
			| tee "${MKPICO_LOG_DIR}/${package}-configure.log"
	fi

	info "Building ${package}"

	logrotate "${MKPICO_LOG_DIR}" "${package}-make.log" "${MKPICO_LOG_HISTORY}"

	if [ "${package}" = "gcc-stage1" ]; then
		make -j${MKPICO_CORES} all-gcc 2>&1 \
			| tee "${MKPICO_LOG_DIR}/${package}-make.log"
	else
		make -j${MKPICO_CORES} all 2>&1 | tee "${MKPICO_LOG_DIR}/${package}-make.log"
	fi

	info "Installing ${package}"

	logrotate "${MKPICO_LOG_DIR}" "${package}-make-install.log" "${MKPICO_LOG_HISTORY}"

	if  [ "${package}" = "gcc-stage1" ]; then
		make install-gcc 2>&1 \
			| tee "${MKPICO_LOG_DIR}/${package}-make-install.log"
	else
		make install 2>&1 \
			| tee "${MKPICO_LOG_DIR}/${package}-make-install.log"
	fi

	popd

	#rm -rf "${MKPICO_BUILD_DIR:?"MKPICO_BUILD_DIR has not been set."}/${package}*"
}

error() {
	local parent_lineno="${1}"
	local message="${2}"
	local code="${3:-1}"

	if [ -n "${message}" ] ; then
		echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
	else
		echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
	fi

	exit "${code}"
}

trap 'error ${LINENO}' \
	ABRT BUS FPE \
	ILL SEGV SYS \
	TRAP XCPU XFSZ

# Parse command line options.
parseOptions "${@}"

# Build up package information.
BINUTILS_PACKAGE="binutils-${BINUTILS_VERSION}.tar.xz"
BINUTILS_SIGNATURE="${BINUTILS_PACKAGE}.sig"

GCC_PACKAGE="gcc-${GCC_VERSION}.tar.xz"
GCC_SIGNATURE="${GCC_PACKAGE}.sig"

GDB_PACKAGE="gdb-${GDB_VERSION}.tar.xz"
GDB_SIGNATURE="${GDB_PACKAGE}.sig"

NEWLIB_PACKAGE="newlib-${NEWLIB_VERSION}.tar.gz"
NEWLIB_SIGNATURE=""

info "Preparing build environment"

# Setup build environment.
mkdir -p "${MKPICO_CROSS_TOOLS}"
mkdir -p "${MKPICO_SOURCE_DIR}"
mkdir -p "${MKPICO_BUILD_DIR}"
mkdir -p "${MKPICO_LOG_DIR}"

#rm -rf "${MKPICO_BUILD_DIR:?"MKPICO_BUILD_DIR has not been set."}/*"

# Ensure CFLAGS are not set during build.
unset CFLAGS

# Download the gnu keyring needed to verify signatures.
# TODO: Downloading with -k is insecure, however currently the gnu cacert does not work.
if ! [ -f "${MKPICO_SOURCE_DIR}/${GNU_KEYRING}" ]; then
	info "Downloading gnu keyring"
	curl -s -L -k -o "${MKPICO_SOURCE_DIR}/${GNU_KEYRING}" "${GNU_MIRROR}/${GNU_KEYRING}" > /dev/null
else
	warning "Using gnu keyring from cache - skipping"
fi

info "Installing packages"

# Download, build and install binutils.
buildPackage "binutils" "${BINUTILS_VERSION}" \
	"${BINUTILS_URL}" "${BINUTILS_PACKAGE}" "${BINUTILS_SIGNATURE}" \
	--target="${MKPICO_TARGET}" \
	--build="${MKPICO_BUILD}" \
	--host="${MKPICO_HOST}" \
	--prefix="${MKPICO_PREFIX}" \
	--mandir=${MKPICO_PREFIX}/share/man \
	--infodir=${MKPICO_PREFIX}/share/info \
	--program-prefix="${MKPICO_TARGET}-" \
	--with-pkgversion="mkpico" \
	--with-tune=cortex-m0plus \
	--with-arch=armv6s-m \
	--with-no-thumb-interwork \
	--with-mode=thumb \
	--with-gnu-as \
	--with-gnu-ld \
	--disable-werror \
	--disable-nls \
	--enable-deterministic-archives

export PATH="${PATH}:${MKPICO_PREFIX}/bin"

# Download, build and install a stage 1 gcc.
buildPackage "gcc-stage1" "${GCC_VERSION}" \
	"${GCC_URL}" "${GCC_PACKAGE}" "${GCC_SIGNATURE}" \
	--target="${MKPICO_TARGET}" \
	--build="${MKPICO_BUILD}" \
	--host="${MKPICO_HOST}" \
	--prefix="${MKPICO_PREFIX}" \
	--infodir=${MKPICO_PREFIX}/share/info \
	--mandir=${MKPICO_PREFIX}/share/man \
	--program-prefix="${MKPICO_TARGET}-" \
	--with-pkgversion="mkpico" \
	--with-tune=cortex-m0plus \
	--with-arch=armv6s-m \
	--enable-languages=c,c++ \
	--enable-c99 \
	--without-headers \
	--without-ppl \
	--without-cloog \
	--with-newlib \
	--with-no-thumb-interwork \
	--with-mode=thumb \
	--with-gnu-as \
	--with-gnu-ld \
	--with-system-zlib \
	--with-newlib \
	--disable-multilib \
	--disable-interpreter \
	--disable-libssp \
	--disable-libgomp \
	--disable-decimal-float \
	--disable-libquadmath \
	--disable-nls \
	--disable-gcj \
	--disable-threads \
	--disable-shared

# Download, build and install libc.
buildPackage "newlib" "${NEWLIB_VERSION}" \
	"${NEWLIB_URL}" "${NEWLIB_PACKAGE}" "${NEWLIB_SIGNATURE}" \
	--target="${MKPICO_TARGET}" \
	--build="${MKPICO_BUILD}" \
	--host="${MKPICO_HOST}" \
	--prefix="${MKPICO_PREFIX}" \
	--with-tune=cortex-m0plus \
	--with-arch=armv6s-m \
	--with-mode=thumb \
	--with-no-thumb-interwork \
	--with-gnu-as \
	--with-gnu-ld \
	--disable-nls \
	--disable-newlib-supplied-syscalls

# Build and install gcc.
buildPackage "gcc" "${GCC_VERSION}" \
	"${GCC_URL}" "${GCC_PACKAGE}" "${GCC_SIGNATURE}" \
	--target="${MKPICO_TARGET}" \
	--build="${MKPICO_BUILD}" \
	--host="${MKPICO_HOST}" \
	--prefix="${MKPICO_PREFIX}" \
	--infodir=${MKPICO_PREFIX}/share/info \
	--mandir=${MKPICO_PREFIX}/share/man \
	--program-prefix="${MKPICO_TARGET}-" \
	--with-pkgversion="mkpico" \
	--with-tune=cortex-m0plus \
	--with-arch=armv6s-m \
	--enable-languages=c,c++ \
	--enable-c99 \
	--with-gnu-as \
	--with-gnu-ld \
	--with-newlib \
	--with-system-zlib \
	--with-build-time-tools=${MKPICO_PREFIX}/${MKPICO_TARGET}/bin \
	--with-mode=thumb \
	--with-no-thumb-interwork \
	--without-ppl \
	--without-cloog \
	--enable-libssp \
	--enable-gnu-indirect-function \
	--disable-multilib \
	--disable-threads \
	--disable-libgomp \
	--disable-gcj \
	--disable-sjlj-exceptions \
	--disable-interpreter \
	--disable-libstdcxx-pch \
	--disable-nls \
	--disable-shared

# Download, build and install gdb.
buildPackage "gdb" "${GDB_VERSION}" \
	"${GDB_URL}" "${GDB_PACKAGE}" "${GDB_SIGNATURE}" \
	--target="${MKPICO_TARGET}" \
	--build="${MKPICO_BUILD}" \
	--host="${MKPICO_HOST}" \
	--prefix="${MKPICO_PREFIX}" \
	--with-tune=cortex-m0plus \
	--with-arch=armv6s-m \
	--program-prefix="${MKPICO_TARGET}-" \
	--with-pkgversion="mkpico" \
	--enable-languages=c,c++ \
	--disable-werror \
	--disable-multilib

info "Logs have been placed in ${MKPICO_LOG_DIR}."
info "Done."
